## **Случайные события. Практическая работа**

### Итоги модуля
В этом модуле было введено понятие **пространства элементарных событий**. Это пространство состоит из различных **исходов** случайной величины. Вероятности элементарных событий в этом пространстве будут принимать значения от 0 до 1. 

В пространстве событий помимо **элементарных** исходов есть также **сложные** события, являющиеся объединением нескольких элементарных. 

Вы также познакомились с **зависимыми** событиями и понятием **условной вероятности**. На основе этого определения строится **формула Байеса**. Она связывает теоретические вероятности осуществления события (**априорная** вероятность) с вероятностями, основанными на некотором опыте (условная или **апостериорная** вероятность). Эта формула позволяет как бы «поменять местами» причину и следствие — получить взаимосвязь между P(A|B) и P(B|A).

Эта практическая работа поможет закрепить полученные знания. В одной части заданий нужно вычислить вероятности сложных событий. Другая часть заданий посвящена применению теоремы Байеса, а также включает в себя краткое знакомство с **наивным байесовским классификатором (НБК)** — одной из моделей машинного обучения.

Основную информацию, необходимую для решения данной практической работы, можно найти в теоретическом разделе этого модуля. Критерии оценки заданий основаны на полноте и правильности решений, а также правильности/неправильности финальных ответов. 

### Цели практической работы
- закрепить полученные знания о вычислении вероятностей сложных событий;
- ближе познакомиться с условными вероятностями, теоремой Байеса и байесовским классификатором.

### Что оценивается
Умение вычислять вероятности сложных событий и вероятности с использованием теоремы Байеса, понимание условных вероятностей. В каждой задаче требуется соотнести набор известных значений вероятностей с условными вероятностями и вычислить новые вероятности. Задача считается решённой, если выполнены все её условия, а также даны правильные ответы на вопросы.

### Как отправить задание на проверку
Выполните задания, сохраните изменения при помощи опции Save and Checkpoint на вкладке меню File или кнопки Save and Checkpoint на панели инструментов. Отправьте итоговый файл Jupyter Notebook (в формате .ipynb) или ссылку на него через форму.

### **Задание 1**

Даны таблицы с суммами и произведениями значений при броске двух кубиков. Используя эти таблицы, вычислите вероятности следующих сложных событий.

<p align="left">
  <img src="https://drive.google.com/uc?id=1If1NDfwPCfLC6JHqxa5IDgXLRzrbB-sI" alt="drawing" width="600"/>
</p>

<p align="left">
  <img src="https://drive.google.com/uc?id=1vWNTqND6br6XzESVSwqKjK9AqeN0-k-4" alt="drawing" width="600"/>
</p>

1. Вероятность, что полученная сумма значений на кубиках — нечётное число.

In [3]:
table_sum = [[i + j for j in range(1, 7)] for i in range(1, 7)]
table_prod = [[i * j for j in range(1, 7)] for i in range(1, 7)]
table_sum

[[2, 3, 4, 5, 6, 7],
 [3, 4, 5, 6, 7, 8],
 [4, 5, 6, 7, 8, 9],
 [5, 6, 7, 8, 9, 10],
 [6, 7, 8, 9, 10, 11],
 [7, 8, 9, 10, 11, 12]]

In [4]:
all_sums = [j for i in table_sum for j in i]
all_prods = [j for i in table_prod for j in i]

all_count = len(all_sums)

even_sums = [i for i in all_sums if i % 2 == 0 ]
odd_sums = [i for i in all_sums if i % 2 != 0 ]
even_sums, odd_sums

([2, 4, 6, 4, 6, 8, 4, 6, 8, 6, 8, 10, 6, 8, 10, 8, 10, 12],
 [3, 5, 7, 3, 5, 7, 5, 7, 9, 5, 7, 9, 7, 9, 11, 7, 9, 11])

In [5]:
prob_1 = len(odd_sums)/all_count
prob_1

0.5

2. Вероятность, что полученная сумма значений на кубиках — число, кратное трём.

In [6]:
odd_3_count = len([i for i in odd_sums if i % 3 == 0])
prob_2 = odd_3_count/all_count
round(prob_2, 2)

0.17

3. Вероятность, что сумма будет меньше пяти или больше десяти.

In [7]:
prob_3 = len([i for i in all_sums if i < 5 or i > 10])/all_count
prob_3

0.25

4. Вероятность, что произведение значений будет равно двенадцати.

In [8]:
prob_4 = all_prods.count(12)/all_count
round(prob_4, 2)

0.11

5. Вероятность, что произведение значений — нечётно.

In [9]:
odd_prods = [i for i in all_prods if i % 2 != 0]
prob_5 = len(odd_prods) / all_count
prob_5

0.25

6. Вероятность, что сумма значений окажется больше или равной их произведению.

In [10]:
is_sum = ['T' if all_sums[i] >= all_prods[i] else 'F' for i in range(len(all_sums))]

prob_6 = round(is_sum.count('T')/all_count, 2)
prob_6

0.33

### **Задание 2**
Загрузите данные о пассажирах «Титаника» из файла titanic.csv в приложенных к практической работе файлах. Ограничьтесь набором таких переменных, как класс билета пассажира, пол и переменной, показывающей, выжил он или нет. В этом датасете все эти переменные заполнены непустым значением.

In [11]:
import pandas as pd
titanic = pd.read_csv("data/train.csv")
X = titanic[['PassengerId','Survived','Pclass','Sex']]
X

     PassengerId  Survived  Pclass     Sex
0              1         0       3    male
1              2         1       1  female
2              3         1       3  female
3              4         1       1  female
4              5         0       3    male
..           ...       ...     ...     ...
886          887         0       2    male
887          888         1       1  female
888          889         0       3  female
889          890         1       1    male
890          891         0       3    male

[891 rows x 4 columns]

1. Запишите в P_fem вероятность, что случайный пассажир «Титаника» — женщина.

In [12]:
P_fem = len(X[X.Sex == 'female'])/len(X)
P_fem

0.35241301907968575

2. Запишите в P_1class вероятность, что случайный пассажир «Титаника» ехал в первом классе.

In [13]:
P_1class = len(X[X.Pclass == 1])/len(X)
P_1class

0.24242424242424243

3. Запишите в P_surv вероятность, что случайный пассажир «Титаника» выжил.

In [14]:
P_surv = len(X[X.Survived == 1])/len(X)
P_surv

0.3838383838383838

4. Запишите в P_fem_surv вероятность, что пассажир — женщина, и одновременно с этим пассажир выжила в катастрофе.

In [15]:
P_fem_surv = len(X[(X['Survived'] == 1) & (X['Sex'] == 'female')]) / len(X)
P_fem_surv

0.2615039281705948

5. Найдите условную вероятность того, что пассажир выживет, при условии, если пассажир — женщина.

In [16]:
# P(A|B) = P(A^B) / P(B), B - женщина
P_cond_surv_fem = P_fem_surv / P_fem
P_cond_surv_fem

0.7420382165605095

6. По аналогии найдите вероятность того, что пассажир выживет, если пассажир ехал в первом классе.

In [17]:
P_1class_surv = len(X[(X['Pclass'] == 1) & (X['Survived'] == 1)]) / len(X)
P_1class_surv

0.1526374859708193

In [18]:
P_cond_surv_1class = P_1class_surv / P_1class
P_cond_surv_1class

0.6296296296296297

7. Найдите вероятность того, что пассажир выживет при условии, что пассажир ехал в первом классе и является женщиной.

In [19]:
P_surv_1class_fem = len(X[(X['Pclass'] == 1) & (X['Survived'] == 1) & (X['Sex'] == 'female')]) / len(X)
P_surv_1class_fem

0.10213243546576879

In [20]:
P_1class_fem = len(X[(X['Pclass'] == 1) & (X['Sex'] == 'female')]) / len(X)
P_1class_fem

0.10549943883277217

In [21]:
P_cond_surv_1class_fem = P_surv_1class_fem /P_1class_fem
P_cond_surv_1class_fem

0.9680851063829786

8. Найдите вероятность того, что пассажир выживет при условии, что пассажир ехал во втором классе и является мужчиной.

In [22]:
P_surv_2class_male = len(X[(X['Pclass'] == 2) & (X['Survived'] == 1) & (X['Sex'] == 'male')]) / len(X)
P_surv_2class_male

0.019079685746352413

In [23]:
P_2class_male = len(X[(X['Pclass'] == 2) & (X['Sex'] == 'male')]) / len(X)
P_2class_male

0.12121212121212122

In [24]:
P_cond_surv_2class_male = P_surv_2class_male / P_2class_male
P_cond_surv_2class_male

0.1574074074074074

9. Используя посчитанные вероятности, найдите вероятность того, что случайно выбранный пассажир — женщина, если мы знаем, что пассажир выжил.

In [25]:
# Формула Байеса: P(A|B) = P(B|A) * P(A) / P(B)
P_cond_fem_surv = P_cond_surv_fem * P_fem / P_surv
P_cond_fem_surv

0.6812865497076023

10. Используя посчитанные вероятности, найдите вероятность того, что случайно выбранный пассажир ехал в первом классе, если мы знаем, что пассажир выжил.

In [26]:
P_cond_1class_1class = P_cond_surv_1class * P_1class / P_surv
P_cond_1class_1class

0.3976608187134503

11. Сравните полученные вероятности с безусловными вероятностями соответствующих событий. Объясните разницу в значениях.

In [27]:
P_1class_surv, P_cond_surv_1class

(0.1526374859708193, 0.6296296296296297)

In [28]:
P_fem_surv, P_cond_surv_fem

(0.2615039281705948, 0.7420382165605095)

Как видно, различия между безусловными и условными вероятностями имеются.

Это связано с тем, что безусловная вероятность находится по всей выборке (женщина & выжила / общее количество человек), а условная относительно условия (женщина & выжила / количество выживших, если мы знаем, что пассажир выжил)

### **Задание 3**
Рассмотрим датасет со статистикой почтового ящика `letters.xlsx`. Данные можно найти в материалах к практической работе. Там содержится 248 записей с информацией о письмах. 

Нам хочется узнать, является ли новое письмо, пришедшее к нам на почту, спамом. Для этого у нас существует статистика писем. Каждое пришедшее письмо может быть либо спамом, либо нет. При этом и спам, и нормальные письма могут содержать слова, характерные для спам-писем. Данный датасет представляет собой набор записей с информацией о пришедших ранее письмах, распознанных человеком как спам или нет.

In [29]:
df = pd.read_excel('data/letters.xlsx', sheet_name='Sheet1', index_col='id_letter')
df

          spam spam_words
id_letter
1           да        нет
2           да         да
3          нет        нет
4          нет         да
5           да         да
...        ...        ...
244        нет        нет
245        нет        нет
246        нет        нет
247        нет        нет
248        нет        нет

[248 rows x 2 columns]

Столбец `spam` отвечает на вопрос, является письмо спамом или нет, `spam_words` — содержит ли оно слова, встречающиеся в спам-письмах.

1. Найдите долю спам-писем по отношению ко всем.

In [30]:
P_spam = len(df[df.spam == 'да']) / len(df)
P_spam

0.3548387096774194

2. Найдите долю писем со спам-подобными словами по отношению ко всем.

In [32]:
P_spam_words = len(df[df.spam_words == 'да']) / len(df)
P_spam_words

0.375

3. Найдите вероятность, что письмо содержит спам-подобные слова при условии, что оно является спамом.

In [40]:
P_spam_spam = len(df[(df['spam'] == 'да') & (df['spam_words'] == 'да')]) / len(df)

P_cond_spam_words_spam = P_spam_spam / P_spam
P_cond_spam_words_spam

0.3636363636363636

4. Найдите вероятность, что письмо является спамом при условии, что оно содержит спам-подобные слова.

In [41]:
P_cond_spam_spam_words = P_cond_spam_words_spam * P_spam / P_spam_words
P_cond_spam_spam_words

0.3440860215053763

С помощью такого принципа [работает наивный байесовский классификатор](https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D0%B9%D0%B5%D1%81%D0%BE%D0%B2%D1%81%D0%BA%D0%B0%D1%8F_%D1%84%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F_%D1%81%D0%BF%D0%B0%D0%BC%D0%B0). При обучении модели для каждого встреченного в письмах слова высчитывается и сохраняется вероятность того, что письмо с этим словом — спам. И в дальнейшем, на основе наличия в письме слов с высокой вероятностью встречающихся в спам-письмах, машина может рассчитать условную вероятность того, что в таком случае письмо является спамом. Если эта вероятность превысит 0,5, можно положить такое письмо в спам. Более сложные модели учитывают не только наличие определённых слов, но и множество других факторов. Тем самым, по целому ряду свойств письма можно рассчитать соответствующую условную вероятность, что письмо будет спамом при условии, что оно обладает некоторым набором характеристик. Такой классификатор работает достаточно хорошо и быстро в простых ситуациях, однако он слишком завязан на варианты значений условий. Например, если в тренировочном датасете не встречалась определённая комбинация условных факторов, то классификатор не сможет оценить вероятность в ситуации, если такая комбинация встретится в тестовой выборке.